# Creating a vector 
you need to create a vector

use numpy to create a one-dimension array

In [20]:
#load library
import numpy as np

#create a vector as a row
vector_row = np.array([1,2,3])

#create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

print(vector_row)
print(vector_column)

print(type(vector_column),type(vector_row))

[1 2 3]
[[1]
 [2]
 [3]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


# Creating a Matrix
you need to create a matrix

use numpy to create a two-dimension array

In [5]:
import numpy as np

#create a vector as a row
matrix = np.array([[1,2],
                   [3,4],
                   [5,6]])

matrix2 =np.mat([[1,2],
                 [1,2],
                 [1,2]])
print(matrix)
print(type(matrix))
print(matrix2)
print(type(matrix2))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
[[1 2]
 [1 2]
 [1 2]]
<class 'numpy.matrix'>


# Creating a Sparse Matrix
given data with very few nonzero values, you want to efficiently  represent it.

In [9]:
import numpy as np
from scipy import sparse
matrix = np.array([[0,0,1],
                   [0,2,0],
                   [3,0,0]])
matrix_sparse =  sparse.csr_matrix(matrix)
print(matrix_sparse)

  (0, 2)	1
  (1, 1)	2
  (2, 0)	3


In [19]:
#create a large matrix
matrix_large = np.array([[0,0,0,0,0,0,0,0,0,0,0,0],
                         [0,1,0,0,0,0,0,0,0,0,0,0],
                         [3,0,0,0,0,0,0,0,0,0,0,0]])
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print("CSR (compressed row)")
print(matrix_large_sparse)

print("------------------------------")

matrix_large2 = np.array([[0,0],
                          [0,1],
                          [3,0],
                          [0,0],
                          [0,0],
                          [0,0],
                          [0,0],
                          [0,0],
                          [0,0]])
matrix_large2_sparse = sparse.csc_matrix(matrix_large2)
print("CSC (compressed column)")
print(matrix_large2_sparse)

print("------------------------------")

matrix_large3_sparse = sparse.lil_matrix(matrix_large)
print("lil (List of lists)")
print(matrix_large3_sparse)

print("------------------------------")

matrix_large4_sparse = sparse.dia_matrix(matrix_large)
print("dia (dictionary of keys)")
print(matrix_large4_sparse)

print("------------------------------")

matrix_large5_sparse = sparse.coo_matrix(matrix_large)
print("coo (COOrdinate formate matrix)")
print(matrix_large5_sparse)

CSR (compressed row)
  (1, 1)	1
  (2, 0)	3
------------------------------
CSC (compressed column)
  (2, 0)	3
  (1, 1)	1
------------------------------
lil (List of lists)
  (1, 1)	1
  (2, 0)	3
------------------------------
dia (dictionary of keys)
  (2, 0)	3
  (1, 1)	1
------------------------------
coo (COOrdinate formate matrix)
  (1, 1)	1
  (2, 0)	3


# Selecting Elements

you need to select one or more elements in a vector or matrix

In [21]:
import numpy as np 
vector = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
#select third element of vector
print(vector[2])

#select second row, second column 
print(matrix[1,1])


3
5


In [70]:
#select all elements of a vector
print(vector[:])
print("---------------------")

#select everything up to and including the third element
print(vector[:1])
print("---------------------")

#select everything after the third element
print(vector[3:])
print("---------------------")

#select the last element
print(vector[-1])
print("---------------------")

#select the first two rows and all columns of a matrix
print(matrix[:2,])
print("---------------------")

#select all rows and the second column 
print(matrix[:,1:2])


[1 2 3 4 5 6]
---------------------
[1]
---------------------
[4 5 6]
---------------------
6
---------------------
[[1 2 3]
 [4 5 6]]
---------------------
[[2]
 [5]
 [8]
 [2]]


# Describing a Matrix

you want to describe the shape, size, and dimensions of the matrix

In [73]:
import numpy as np
matrix = np.array([ [[1,2,3],
                     [5,6,7],
                     [6,6,6]],
                    [[1,2,4],
                     [1,4,5],
                     [2,4,5]]
                  ])
    
print(matrix.shape)
print(matrix.size)
#返回维度 dimensions
print(matrix.ndim)
print("--------------")
m = np.array([[[[1]]]])
print(m.shape)
print(m.size)
print(m.ndim)

(2, 3, 3)
18
3
--------------
(1, 1, 1, 1)
1
4


# Applying Operations to Elements

you want to apply some function to multiple elements in an array

In [52]:
#load library
import numpy as np 
#create matrix
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

#create a function that adds 100 to something 
#匿名函数lambda：是指一类无需定义标识符（函数名）的函数或子程序。
#lambda 函数可以接收任意多个参数 (包括可选参数) 并且返回单个表达式的值。
#def add_100(sth):
#   return sth + 100
add_100 = lambda sth:sth+100

#Create vectorized function 将函数向量化
vectorized_add_100 = np.vectorize(add_100)

array = vectorized_add_100(matrix)
print(array)

print("--------------------------------")

array1=add_100(matrix) #broadcasting  --> array1 = matrix +100
print(array1)

[[101 102 103]
 [104 105 106]
 [107 108 109]]
--------------------------------
[[101 102 103]
 [104 105 106]
 [107 108 109]]


# Finding the Maximum and Minimum Values

you need to find the maximum or minimum value in an array

In [29]:
import numpy as np 
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(np.max(matrix))

print(np.min(matrix))

9
1


In [30]:
#find maximum element in each column----0 ->列  1 ->行
array = np.max(matrix,axis=0)
print(array)
#find maximum element in each row
array = np.max(matrix,axis=1)
print(array)

[7 8 9]
[3 6 9]


# Calculating the Average, Variance, and Standard Deviation

you want to calculate some descriptive statistics about an array

In [31]:
#load library 
import numpy as np 
#create matrix
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
#return mean (平均值)
average = np.mean(matrix)
print(average)

#return variance
variance = np.var(matrix)
print(variance)

#return standard deviation
standard_deviation = np.std(matrix)    
print(standard_deviation)

5.0
6.666666666666667
2.581988897471611


just like with the max and min, we can easily get descriptive statistics about the whole matrix or do calculations along a single axis：

In [32]:
#find the mean value in each column----0 ->列  1 ->行
mean_eachColumn = np.mean(matrix,axis=0)
print(mean_eachColumn)

[4. 5. 6.]


# Reshaping Arrays

you want to change the shape (number of rows and columns) of an array without changing the elements values

In [65]:
import numpy as np 

#create 4x3 array
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [1,2,30]])

#reshape matix into 2x6
array = matrix.reshape(2,6)
print(array)

[[ 1  2  3  4  5  6]
 [ 7  8  9  1  2 30]]


In [66]:
array = matrix.reshape(1,-1)
print(array)
print(type(array))
print(array.shape)
print(array.size)
print(array.ndim)


[[ 1  2  3  4  5  6  7  8  9  1  2 30]]
<class 'numpy.ndarray'>
(1, 12)
12
2


In [63]:
array1 = matrix.reshape(matrix.size)
print(array1)
print(type(array1))
print(array1.shape)
print(array1.size)
print(array1.ndim)

[ 1  2  3  4  5  6  7  8  9  1  2 30]
<class 'numpy.ndarray'>
(12,)
12
1


In [67]:
array = matrix.reshape(-1,1)
print(array)
print(type(array))
print(array.shape)
print(array.size)
print(array.ndim)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [ 1]
 [ 2]
 [30]]
<class 'numpy.ndarray'>
(12, 1)
12
2


# Transposing a Vector or Matrix

you need transposing a vector or matrix

In [46]:
import numpy as np
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

#transposing matrix
array = matrix.T
print(array)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [47]:
array = np.array([1,2,3,4,5,6]).T
print(array)

[1 2 3 4 5 6]


from above, we can see that a vector can not be transposed, because it is just a collection of values

In [49]:
array = np.array([[1,2,3,4,5,6]]).T
print(array)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# Flattening a Matrix
you need to transform a matrix into a one-dimentional array

In [50]:
import numpy as np 
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
array = matrix.flatten()#-->matrix.reshape(1,-1)
print(array)

[1 2 3 4 5 6 7 8 9]


# Finding the Rank(秩) of a Matrix

In [51]:
import numpy as np
matrix = np.array([[1,2,3],
                   [3,4,5],
                   [6,7,15]])

matrix_rank = np.linalg.matrix_rank(matrix)
print(matrix_rank)

3


# Calculating the Determinant(行列式)

In [52]:
matrix_determinant = np.linalg.det(matrix)
print(matrix_determinant)

-14.000000000000004


# Getting the Diagonal(对角线) of a Matrix

In [53]:
matrix_diagonal = matrix.diagonal()
print(matrix_diagonal)

[ 1  4 15]


In [54]:
#return diagonal one above the main diagonal
above_diagonal = matrix.diagonal(offset = 1)
print(above_diagonal)

#return diagonal one below the main diagonal
below_diagonal = matrix.diagonal(offset = -1)
print(below_diagonal)

[2 5]
[3 7]


# Calculating the Trace of Matrix
矩阵的迹 = 对角线值相加

In [55]:
matrix_trace = matrix.trace()
print(matrix_trace)

20


In [56]:
#return diagonal and sum elements
matix_trace1 = sum(matrix.diagonal())
matix_trace1

20

# Finding Eigenvalues and Eigenvectors
特征值和特征向量

In [58]:
import numpy as np 
matrix = np.array([[1,-1,3],
                   [1,1,6],
                   [3,8,9]])

eigenValues, eigenVectors = np.linalg.eig(matrix)
print(eigenValues)
print(eigenVectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


# Calculating Dot Products(点积)

In [63]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

dot_product = np.dot(vector_a,vector_b)
dot_product

32

In [64]:
vector_b@vector_a  #Python 3.5+

32

# Adding and subtracting Matrix

In [65]:
import numpy as np 
matrix_a = np.array([[1,1,1],
                     [1,2,2],
                     [1,1,1]])
matrix_b = np.array([[1,3,1],
                     [1,3,2],
                     [1,3,1]])

In [66]:
np.add(matrix_a,matrix_b)

array([[2, 4, 2],
       [2, 5, 4],
       [2, 4, 2]])

In [67]:
np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -1,  0],
       [ 0, -2,  0]])

In [68]:
matrix_a+matrix_b

array([[2, 4, 2],
       [2, 5, 4],
       [2, 4, 2]])

In [69]:
matrix_a-matrix_b

array([[ 0, -2,  0],
       [ 0, -1,  0],
       [ 0, -2,  0]])

# Multiplying Matrixs

In [70]:
import numpy as np

matrix_a = np.array([[1,1],
                     [1,2]])
matrix_b = np.array([[1,3],
                     [1,2]])

In [71]:
np.dot(matrix_a,matrix_b)

array([[2, 5],
       [3, 7]])

In [72]:
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [73]:
#multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

# Inverting a Matrix(求逆矩阵)

In [74]:
import numpy as np 
matrix = np.array([[1,4],
                   [2,5]])
np.linalg.inv(matrix)


array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [75]:
#AA^-1=I
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

# Generating Random Values

In [69]:
import numpy as np 

print(np.random.random(1))
print(np.random.random(1))

#seed 种子，设置种子之后在相同的种子下面生成的随机数一样，并且多次生成都是同一个数
#set seed
np.random.seed(10)
print(np.random.random(1))

#set seed
np.random.seed(10)
print(np.random.random(1))

[0.01947524]
[0.46321853]
[0.77132064]
[0.77132064]


In [86]:
#Generate three random intergers between 1 and 10
np.random.randint(0,11,3)

array([4, 0, 1])

In [88]:
#Generate three numbers from a normal distribution(正态分布) with mean 0.0
#and standard deviation(标准差) of 1.0
np.random.normal(0.0,1.0,3)

array([-0.60555494, -0.65099088,  0.51256776])

In [89]:
#Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0,1.0,3)

array([-2.33407641,  0.77851428,  3.01828425])

In [74]:
#Draw three number greater than or equal to 1 and less than 2(大于等于1，小于2)
np.random.uniform(1.0,2.0,3)

array([1.02075195, 1.63364823, 1.74880388])